[general]
import = [
    "~/.config/alacritty/custom/themes/gruvbox_material_hard_dark.toml",
]

[window]
startup_mode = "Maximized"
# for MacOS
option_as_alt = "Both"
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "SemiBold" }
size = 15.75

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true 

[keyboard]

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "None"

[[keyboard.bindings]]
key = "B"
mods = "Alt"
chars = "\\u001bb"

