# display on prompt
format = '''
[\[](#00c7bc)$username$hostname $directory[\]](#00c7bc)[\$](#4ee64f) 
'''

right_format = '''
$git_branch$git_status
'''


# do not insert new line after pressing enter.
add_newline = false

[character]
success_symbol = '[\$](cyan)'

[hostname]
format = '[$hostname](#25d366)'
ssh_only = false

[username]
format = '[$user](yellow)[@](#e33e30)'
show_always = true

[directory]
format = '[$path](#f170ed)'
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ' '
format = ' [$symbol](#ff6ca6)[$branch](#12c00d) '

