# display on prompt

format = '''
$username$hostname $directory [|](#FE5F57) 
'''

right_format = '''
$git_branch
'''

# do not insert new line after pressing enter.
add_newline = false

[character]
success_symbol = '[\$](cyan)'

[hostname]
format = '[$hostname](#AFA9A3)'
ssh_only = false

[username]
format = '[$user](#CAB062)[@](#7F8B89)'
show_always = true

[directory]
format = '[$path](#CAB062)'
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ' '
format = ' [$symbol](#ff6ca6)[$branch](#A8B665) '

